# fly.toml app configuration file generated for mysummarybot-sparkling-sun-9815 on 2024-12-03T20:10:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mysummarybot-sparkling-sun-9815'
primary_region = 'ams'

[build]



[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "mysummarybot_data"
  destination = "/data"
